package tp7;

import java.util.ArrayList;
import java.util.Random;

public class Main {

	// Number of objects to generate
	public static final int ETUD_COUNT = 5_000_000;
	
	// Number of benchmarking iterations per thread count
	public static final int SAMPLES = 10;

	public static void main(String[] args) throws InterruptedException {

		for (int threadCount = 1; threadCount <= 15; ++threadCount) {
			long meanTime = 0;
			
			for (int sample = 0; sample < SAMPLES; ++sample) {
				
				// Number of objects handled by a single thread
				final int batchCount = ETUD_COUNT / threadCount;

				// Lists of generated objects
				final ArrayList<ArrayList<Etudiant>> lists = new ArrayList<>();
				
				// List of generator threads
				final ArrayList<Thread> threads = new ArrayList<>();

				long c1 = System.nanoTime();

				for (int i = 0; i < threadCount; ++i) {
					
					// Dummy capture variable
					final int batchNum = i;
					
					// List of objects generated by this thread
					final ArrayList<Etudiant> list = new ArrayList<>();
					
					// The thread itself
					final Thread thread = new Thread(new Runnable() {
						@Override
						public void run() {
							final Random rng = new Random();
							
							// Account for the last batch which may be smaller due to rounding
							final int first = batchNum * batchCount, last = Math.min(first + batchCount, ETUD_COUNT);
							
							// Plain synchronous generation
							for (int i = first; i < last; ++i)
								list.add(EtudiantGenerator.generate(rng));
						}
					});

					// Register the thread and its output list, and start it
					lists.add(list);
					threads.add(thread);
					thread.start();
				}

				// Final output
				final ArrayList<Etudiant> finalList = new ArrayList<>();

				// Join each thread and concatenate the output lists
				for (int i = 0; i < threadCount; ++i) {
					threads.get(i).join();
					finalList.addAll(lists.get(i));
				}

				long c2 = System.nanoTime();
				
				// Update mean time
				double sampleWeight = 1.0 / (sample + 1);
				meanTime = (long) ((1.0 - sampleWeight) * meanTime + sampleWeight * (c2 - c1));
				
				System.out.print('.');
			}
			System.out.println("Mean time taken by " + threadCount + " threads in "+ SAMPLES +" samples : " + meanTime / 1_000_000_000.0f + "s");
		}
	}
}
